[package]
name = "cunk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
argparse = "0.2.2"
itertools = "0.10"
rand = "0.8"
